### ISSUE TITLE
Safari中导航栏显示异常

### ISSUE THREAD

**Issue by ZhuGongpu** [QMUI/qmui_web#1]
http://qmuiteam.com/web/ 在Safari中导航栏没有对齐。
![ff7cfe40-a55d-4066-891d-9dbfecc3b129](https://cloud.githubusercontent.com/assets/7722194/17641409/3ce537c0-6151-11e6-9bc1-c893bf9e56eb.png)

**Comment by kayo5994** [comment]
已经[修复了该问题](https://github.com/QMUI/qmuidemo_web/commit/a92f759a04d99eb448d95c0dcd2b2e4c54849be1)。
http://qmuiteam.com/web/  是 [qmuidemo_web](https://github.com/QMUI/qmuidemo_web) 的副本，相关 Issues 可以提到那边。
