### ISSUE TITLE
web font 有支持的计划么？

### ISSUE THREAD

**Issue by MicroJes** [QMUI/qmui_web#11]

**Comment by kayo5994** [comment]
请问 Web Font 的支持是指 Icon Font 制作还是单纯地使用 Font-Face 呢？
如果是单纯地使用 Font-Face，目前我们是使用[字蛛](http://font-spider.org/)这个工具。
而 Icon Font 这种属于偏业务细节的需求，不太适合由框架提供，毕竟 Icon 的种类可以有很多，框架无法做到完全满足需求，建议由业务实现。
