### ISSUE TITLE
ui项目图片要放置到哪里呢？我放到ui_dev-project-images目录下不会自动发布到public中啊？

### ISSUE THREAD

**Issue by vb3064** [QMUI/qmui_web#12]
在提交 Issues 时，请尽量添加以下信息，这将有助于你的 Issues 能更及时、更妥当地被回复和解决。另外，可以检查你所运行的 QMUI Web 版本是否为 **最新版本**，因为问题可能已经被修复。

以上为提交 Issues 的模板说明文字，提交 Issues 时请删除。

----

### 运行环境 ###

- [x] 操作系统版本：`macOS (10.x)` / `Windows (7/8/10)` / `Linux` / `其他（自行填写具体系统）`
- [x] QMUI Web 版本：`1.x.x`
- [x] Node.js 版本：`4.x.x`

**Comment by kayo5994** [comment]
如果图片无需雪碧图处理，请你将图片放置到 UI_dev/project/images/independent 目录，这样图片会自动发布到 public/style/images/independent 目录并进行压缩处理。如果需要雪碧图处理，则可以使用[扩展组件](http://qmuiteam.com/web/page/widget.html#qui_widget_autoSprite)。
关于图片文件管理的完整介绍可以参考[这里](http://qmuiteam.com/web/page/start.html#qui_imagesManage)。

**Comment by vb3064** [comment]
谢谢。问题已解决，图片文件名不能有中文，有中文不能识别。
