### ISSUE TITLE
qmui 无法编译sass文件，

### ISSUE THREAD

**Issue by fadingchen** [QMUI/qmui_web#13]
### 运行环境 ###

- [x] 操作系统版本： `Windows (10)`
- [x] QMUI Web 版本：`2.0`
- [x] Node.js 版本：`6.x.x`

### 具体问题描述 ###

sass文件无法编译 

#### 问题截图 ####
![image](https://cloud.githubusercontent.com/assets/6983781/26195693/35cd62ea-3bef-11e7-9843-d595b0c9f1e9.png)

**Comment by kayo5994** [comment]
我们刚刚更新了 [2.1.0](https://github.com/QMUI/QMUI_Web/releases/tag/2.1.0) 版本，其中也修复了这个问题，请更新到该版本。
