### ISSUE TITLE
样式的疑问

### ISSUE THREAD

**Issue by DmcSDK** [QMUI/qmui_web#14]
组件有些许少，还有样式好像在移动端能用，但好像不咋好看呀，比如树状下拉菜单，还有qui_inputext上边框有个难看的阴影。
我是用iphone7 plus ios10.3.3自带游览器测试。
是不是应该各个组件在各大平台上要不同样式，
1.比如qui_tab：在IOS应该对应原生UISegmentedControl这种样式，在安卓上应该对应原生android.support.design.widget.TabLayout  样式
2.树状选择菜单，在移动端好像很难用

**Comment by kayo5994** [comment]
感谢你的反馈和建议。QMUI Web 的设计核心是"帮助开发者快速建立属于项目自己的 UI"，而不是“UI 组件的合集”，所以本身自带的组件不多，而且样式都比较简单，它的使用方式是通过与 Sass 的工具方法和工作流的配合，尽量帮助开发者快速制作属于一个项目的独立样式，如果框架本身带有大量复杂的组件，当需要构建项目的独立 UI 时，反而会造成干扰（如造成样式浪费，原有样式需要被覆盖等）。
因此各个组件最终需要表现出怎样的外观，是取决于你的项目设计，QMUI Web 会在其中充当辅助开发的作用。
关于 QMUI Web 设计核心的介绍，有兴趣的话可以参考[这里](https://mp.weixin.qq.com/s?__biz=MzIwMzYwMjkzOQ==&mid=2247484005&idx=1&sn=a370de8c5b82b1368cff8aeb94a82947&chksm=96cdacf1a1ba25e7f28105e6c92a3b2a58fd15a0079658c3d78a5af8b21669b85e6f7bdefd79&mpshare=1&scene=1&srcid=0911NCLk8j75pH8WPAJy3mXc&key=fe004993bdfc779cb2da6aaf5f80ce6cc7593a753eb8ba669a3ac4382b285a11e37a4f81ca1943ee348db50b2253edca8db3b00affa5d19f1273235235408d5f216f4edf145a0b0d28f97b858bd08aeb&ascene=0&uin=MjM1NjA5NzI4MA%3D%3D&devicetype=iMac17%2C1+OSX+OSX+10.12.5+build(16F73)&version=12000902&nettype=WIFI&fontScale=100&pass_ticket=qmVbDp2LhYVwXrRER6YN%2Fu3smtFUWSEDS7xpYXeG4c6BITOJG9Ns%2FKIkxZWMEv0c)。

**Comment by DmcSDK** [comment]
噢原来是这样的设计目的啊，听起来蛮不错的。好吧我起初理解成这就是一个类似手机QQ风格的UI库组件合集，谢谢解答。

**Comment by kayo5994** [comment]
嗯，可能是名字里的 Q 也会容易让人联想到 QQ UI 库，其实 QM 是 QQMail 的意思，因为我们团队之前主要是做邮箱的，名字就一直沿用下来了。
