### ISSUE TITLE
yo qmui创建项目后，直接gulp运行环境，样式文件丢失

### ISSUE THREAD

**Issue by lancelot-song** [QMUI/qmui_web#15]
### 具体问题描述 ###
cnpm install -g generator-qmui
yo qmui后创建的目录为
├─public
├─UI_dev
│  └─qmui_web     // QMUI Web 主源码应放置在这一层目录
├─UI_html
└─UI_html_result

public目录为空 、UI_dev子目录不存在project文件夹
导致gulp、gulp sass运行时不报错

虽然环境、页面正常运行，但就是拿不到CSS

后来查了下gulp配置，自己得先执行一下 gulp initProject重新初始化一次项目才行
再gulp就没问题了。。

**Comment by kayo5994** [comment]
能否提供一下操作系统版本、generator-qmui 版本、Node.js 版本这三个信息？

**Comment by lancelot-song** [comment]
node v4.2.2
generator-qmui@2.3.0
windows10 版本1703（OS 内部版本 15063.540）

**Comment by kayo5994** [comment]
@lancelot-song 因为没有具体的报错信息，猜测可能是两个原因导致的：一是 Node.js 版本较低导致的问题，你可以尝试升级到目前官网的推荐版本 6.11.3 再重新执行 yo qmui；二是执行 yo qmui 的终端没有使用管理员权限运行，因为部分 QMUI 依赖包需要依赖管理员权限执行脚本进行安装，所以建议是使用管理员权限运行。
