### ISSUE TITLE
萌新求指导～

### ISSUE THREAD

**Issue by AdminTestsGitHub** [QMUI/qmui_web#17]
大佬好，打扰大佬了，我是一名iOS开发者，目前在VX QMUI交流群里面，想接触一下web的东西，下载了QMUI_web，也部署好了，但是还不太会用，我试着去修改UI_html里面的index.html文件，着实是生效了，并且在UI_result里面生成了对应的文件。但是我在修改public.style.css.main.css 即时也是生效的。问题来了，**我再一次gulp start的时候，对应css的修改又被恢复在原来的状态**。貌似得在project文件夹里面进行业务修改(css修改)么？萌新还不太了解这个机制，能否稍微指导一下，我现在只是想通过直接修改demo的文件，来了解一下web的东西，暂时只是想搭一个个人网站，但是也没太多的精力搞，只能先这样了。麻烦大佬了。 我就是想通过修改一些文件，达到我想要UI就可以，请问我需要在哪修改css样式？

**Comment by kayo5994** [comment]
QMUI Web 的运行机制是编写 Sass 文件，从 Sass 文件经过构建输出样式文件，而 Sass 文件作为一种预处理格式，通常是跟输出的样式文件分开存放的。在 QMUI Web 的默认结构里，Sass 文件放在 UI_dev/project 里，主入口是 main.scss，里面通过 Sass 的 import 语法引入了各个公共组件和业务代码，你需要修改的，正是这部分代码。当 QMUI 的 gulp 任务正在运行时，会自动编译你的修改，输出到 public/style/css 目录中。

因此，对于你的主要问题：“我在修改public.style.css.main.css 即时也是生效的。问题来了，我再一次gulp start的时候，对应css的修改又被恢复在原来的状态。”，需要做的就是修改 UI_dev/project 中的 Sass 文件而不是直接修改 public 中的 CSS 文件。

而对于：“想通过修改一些文件，达到我想要UI就可以”，则可以直接修改 UI_dev/project/_var.scss 中的各个变量，这些变量被应用于各个公共组件和基础样式中，只要修改变量值，可以快速调整项目的 UI，这个也是 QMUI Web 的一项主要功能。

**Comment by AdminTestsGitHub** [comment]
多谢大佬耐心指导，感谢QMUI团队，可以让开发者在刚入门的阶段就可以接触到这么优秀的编程方式，编程思想。致敬开源！

**Comment by AdminTestsGitHub** [comment]
萌新再次打扰，熟悉并研究了一段时间，仍然有一些问题想不明白。举例说明：1.图片资源在哪里引用的？我只在编译之后的main.css文件里看到了引用，但是开发目录文件夹下找不到引用的地方，比如说frame_head_title 引用的 "TopLogo.png"。2.如何连接数据库，配置数据库，在哪写网络请求，从而获取数据生成列表页（html文件）。萌新再次感谢，也可以推荐一些资料，萌新研究研究～多谢～

**Comment by kayo5994** [comment]
1. 图片资源在 Demo 里是使用了 Sprite 的图片处理方式，把多个小图拼成一个大图，减少图片请求数，“TopLogo.png” 这张图片通过 QMUI 的工作流处理，直接读取文件的信息输出 Sprite 的处理结果。所以开发的时候无需对图片进行引用，直接按格式写 class 即可，这个也是 QMUI 的一个比较常用的功能，可以参考[内置工作流 - QMUI Web](http://qmuiteam.com/web/page/scaffold.html#qui_scaffoldSprite)，Sprite 的概念可以自行搜索。
2. QMUI Web 是 UI 框架，不涉及“连接数据库，配置数据库，写网络请求”这些部分，这些内容自行搜索也是有很多的入门解决方案。

**Comment by AdminTestsGitHub** [comment]
请问如何配置config.js 的 browserSyncProxy 等相关的配置选项来达到这样的一个需求：“在浏览器上直接输入域名地址（http://www.qmuiteam.com/），直接跳转域名解析到的服务器上，访问 8080/web/index.html"? 萌新再次打扰～

**Comment by kayo5994** [comment]
@AdminTestsGitHub browserSyncProxy 仅用来搭建服务，无法配置域名，域名跳转应该用 Nginx / Apache 等工具配置，把域名指向你的服务。

**Comment by XIAOGUIGUI** [comment]
模板重新include之后需要手动刷新。这个有解决过?

**Comment by kayo5994** [comment]
@XIAOGUIGUI 是指模板 include 子模板后，没有自动刷新浏览器？还是说没有更新结果模板？

**Comment by XIAOGUIGUI** [comment]
更新结果模板后，浏览器看到的是久的东西，要手动再刷新一下才是最新的.是我的使用的姿势有问题？

**Comment by kayo5994** [comment]
@XIAOGUIGUI XI 使用默认的 QMUI Web 配置，应该是自动启用了 browserSync，修改模板后会自动刷新的。能否贴一下 QMUI Web 版本号以及 `UI_dev/qmui.config.js` 中 `browserSync` 的内容。

**Comment by AdminTestsGitHub** [comment]
![image](https://user-images.githubusercontent.com/32261136/43387063-0b720a14-9418-11e8-8404-977b8ce87ba9.png)
请问大佬，按照QMUIDemo_web项目的文件路径， nginx.config 文件的location那块应该怎么配置？我现在加载不出来css/js/图片等资源文件，大佬能否帮小弟看一下。

**Comment by kayo5994** [comment]
@AdminTestsGitHub QMUI Web 是前端的框架，它提供的是前端的构建服务，因此目前 QMUI Demo 的结构中，实际上没有服务端的相关文件，如果只是想基于 Demo 简单运行 Nginx，建议可以把 location 的 root 指向项目根目录，然后通过“域名/UI_html_result”访问主页。

**Comment by AdminTestsGitHub** [comment]
请问大佬js的逻辑在哪里写？比如我想从A页面（一些a标签列表）点击一个a标签，传递不同的参数到B页面（详情页，根据不同的参数加载不同内容），我应该怎么实现呢？在开发目录里面找不到js的代码呀，是不是有其他的方式呢？

**Comment by AdminTestsGitHub** [comment]
补充上一条：css - html如何在src=“ ”的图片地址上写一个变量呢?
