### ISSUE TITLE
什么时候支持vue,webpack?

### ISSUE THREAD

**Issue by cornucopib** [QMUI/qmui_web#18]
### 运行环境 ###

- [x] 操作系统版本：`macOS (10.x)` / `Windows (7/8/10)` / `Linux` / `其他（自行填写具体系统）`
- [x] QMUI Web 版本：`1.x.x`
- [x] Node.js 版本：`4.x.x`

**Comment by kayo5994** [comment]
QMUI Web 没有计划制作一个 Webpack 的版本，请问你指的是怎样的支持方式呢？
如果是需要一个 Webpack 版的工作流，按 Webpack 4 的使用方式，我们比较推荐按需自行编写一份配置，而不是使用第三方的工作流。
而 Sass 工具方法已经抽取成独立的依赖包 [QMUI_Sass](https://github.com/QMUI/QMUI_Sass)，可自行安装使用。
