### ISSUE TITLE
加入我们 页面404

### ISSUE THREAD

**Issue by zxhycxq** [QMUI/qmui_web#19]
### 具体问题描述 ###
https://qmuiteam.com/join-us/  页面404

#### 问题截图 ####
![image](https://user-images.githubusercontent.com/11674203/62509641-7f9d2900-b83e-11e9-8ebd-580bc761773a.png)

**Comment by kayo5994** [comment]
本次招聘已经结束，没有及时下线”加入我们“页面入口，感谢关注。
