### ISSUE TITLE
text_multiLine_ellipsis兼容性问题及末行间距Bug

### ISSUE THREAD

**Issue by ucaime** [QMUI/qmui_web#2]
在firefox47中无效，测试结果如图：
![02](https://cloud.githubusercontent.com/assets/3446052/17685061/4b4a85b0-6393-11e6-9570-1c5f081b7775.png)
另外请注意上图，我设置的行高为60px，2行。chrome及safari中当启用两行限制后，明显发现两行的截断最后一行是会忽略行高的，这就意味着在不确定内容是一行还是多行的时候，该元素与下面的元素间距无法被合理控制。

**Comment by kayo5994** [comment]
关于第一点 Firefox 下无效，这个确实会这样，目前 CSS 多行省略号的解决方案都依赖于 line-clamp: 2，这个属性目前只有 Webkit 和 Blink 内核支持。

关于第二点，已经修正了，解决方法可以参考关联的代码。效果如下（即统一表现为最后一行底部都会出现行高）。
![image](https://cloud.githubusercontent.com/assets/2270639/17694382/286259ea-63d6-11e6-957c-3d76ee79146e.png)

当然这个方案本身也不完美，如果设置为 3 行，但实际内容只有两行，那么因为 after 的引入会产生多余空白。因此 text_multiLine_ellipsis 这类纯 CSS 的解决方案只适用于固定行数的多行省略号。

**Comment by ucaime** [comment]
这个修改方案并没有解决问题。正如你所说的，仅仅用于固定行数。但一般我遇到的情况都是不确定文字字数的情况下，我设置最多显示2行，当只有一行的时候高度正常就是一行。text_multiLine_ellipsis的使用场景也应该如此。

现阶段只能依赖js去处理了。我无法确定这是不是 -webkit-line-clamp本身设计缺陷导致的，在官方的issues里我提交了这个问题。正常的处理逻辑应该不会选择仅仅裁切到文字边缘而忽略掉本身的行高属性。

**Comment by kayo5994** [comment]
关于“裁切到文字边缘而忽略掉本身的行高属性”这一点应该是 -webkit-line-clamp 本身的 bugs，单纯从这个属性的设计意图来看，它完全没有必要去干预行高的表现，只控制好行数就好了。

**Comment by ucaime** [comment]
你现在处理的方法感觉没有太多必要。既然固定行数才能使用，还不如直接将代码中的`max-height`更改为`height`来暴力处理。

**Comment by kayo5994** [comment]
嗯，直接改成 height 这个方法的定位会更加明确
