### ISSUE TITLE
执行yo qmui 报错了~！求解~

### ISSUE THREAD

**Issue by zhilianbi520** [QMUI/qmui_web#4]
![2888838257 chatroom_1473304262621_17](https://cloud.githubusercontent.com/assets/16549630/18336176/ae9f699c-75b7-11e6-8fa5-7a5695babc83.png)
到compass就报错。~！

**Comment by kayo5994** [comment]
看截图中的日志 QMUI 已经是已经安装好了，可能是本地的 Compass 有问题，你可以进入 UI_dev/qmui_web/workflow/task/compass.js，把

```
compass compile -q
```

修改成

```
compass compile
```

保存后在 qmui_web 目录执行 `gulp`，这时候再截图一下完整的报错内容。

**Comment by zhilianbi520** [comment]
![2888838257 chatroom_1473328694309_80](https://cloud.githubusercontent.com/assets/16549630/18345515/77ce3fce-75ee-11e6-8fbe-459fb1f98b69.png)
装的是1.0.3 版本的compass

**Comment by zhilianbi520** [comment]
上图为已修改完的报错。

**Comment by kayo5994** [comment]
是 Sass 引用路径出错了，似乎是 path 获取 Windows 下的相对路径引发了 bug，麻烦你先手工修改 UI_dev/project/main.scss 中的引入 QMUI 路径，修改为：

``` sass
// 引入 QMUI
@import "../qmui_web/qmui/_qmui.scss"
```

这样 Compass 应该就可以编译通过了，源码那边我再修复一下。

**Comment by zhilianbi520** [comment]
好的。多谢~！已解决~

**Comment by kayo5994** [comment]
源码已修复，新项目可以直接使用 yo qmui 安装。
