### ISSUE TITLE
QMUI web工具运行GULP出错

### ISSUE THREAD

**Issue by calcyu** [QMUI/qmui_web#6]
[13:31:26] 开启 Gulp 服务...
'gulp' �����ڲ����ⲿ���Ҳ���ǿ����еĳ��� 
���������ļ��� 
child process exited with code 1[13:31:26] Gulp 进程意外关闭，请重新启动服务

**Comment by kayo5994** [comment]
你打的内容乱码了，我只能猜测，应该是没有在项目中安装 QMUI Web 的依赖包，或者依赖包安装不全，可以尝试在项目的 UI_dev/qmui_web 目录中删除 node_module 目录（如果没有这个目录说明没有安装依赖包），然后执行 `npm install` 命令重新安装依赖包。
另外建议直接使用 QMUI 的 Yeoman 脚手架 generator-qmui 来配置 QMUI，该工具会自行完成所有项目配置和依赖包安装：

```
#安装 Yeoman，如果本地已安装可以忽略
npm install -g yo
#安装 QMUI 的模板
npm install -g generator-qmui
#在项目根目录执行以下命令
yo qmui
```

**Comment by calcyu** [comment]
感谢抽空回复，项目依赖包是正常的 我用Webstorm可以正常使用，使用QMUI Web工具直接乱码，感觉和环境有关，web工具调用Gulp出错了 出错日志乱码 我也不晓得是什么原因，我再研究一下

**Comment by kayo5994** [comment]
好的，可以试试把系统终端编码改成 UTF-8，直接在终端中调用 QMUI 的 Gulp 命令，看看输出日志的编码是否正确。
