### ISSUE TITLE
官网都打不开？

### ISSUE THREAD

**Issue by wzlee** [QMUI/qmui_web#7]

**Comment by menduo** [comment]
ping 不通了。

**Comment by kayo5994** [comment]
![image](https://cloud.githubusercontent.com/assets/2270639/19672652/11676c7e-9aab-11e6-9238-d0610ec67fe4.png)

我刚刚尝试了是可以 ping 的，浏览器访问也正常，你们现在再尝试一下能否访问？

**Comment by wzlee** [comment]
![image](https://cloud.githubusercontent.com/assets/4182865/19674276/9603c74e-9ab9-11e6-8aa4-ad3c6f58dec4.png)
![image](https://cloud.githubusercontent.com/assets/4182865/19674317/cf0bab06-9ab9-11e6-83af-7cf3bd8a4ac7.png)

**Comment by kayo5994** [comment]
ping 是作用于 host 的，不是作用于 URL，不能带 / ping
