### ISSUE TITLE
框架的输出样式文件只能一个吗？

### ISSUE THREAD

**Issue by alabrother** [QMUI/qmui_web#9]
### 具体问题描述 ###
现实的项目是，比如我的首页需要一个公共样式文件，和一个专有样式文件，列表页也是这种情况，我该如何配置？

**Comment by kayo5994** [comment]
QMUI 推荐使用单一个样式文件的方式去写页面，公共样式文件放到 UI_dev/project/widget 目录，各个业务的专有样式文件放到 UI_dev/project/logic 目录，最后统一 import 到 main.scss，这也是 Sass 本身推荐的方式。
如果你确实需要多个独立的样式表，也可以在 main.scss 平级建立多个文件，像 main.scss 那样 import QMUI 的工具方法和组件文件，然后编写样式就可以了，QMUI 会一并编译这些 Scss 文件。

**Comment by alabrother** [comment]
多谢回复，不好意思，我应该多动手试试！麻烦了！

**Comment by kayo5994** [comment]
不客气，有问题欢迎提问！
